config/routes.rb
Rails.application.routes.draw do
  get 'users/dashboard'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :games do
    resources :bookings
    resources :reviews
  end

  get 'dashboard', to: 'users#dashboard', as: :dashboard
  patch 'accept/:id', to: 'bookings#accept', as: :accept_booking
  patch 'deny/:id', to: 'bookings#deny', as: :deny_booking

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :game
  belongs_to :user
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many_attached :photos, dependent: :destroy
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :game

  validates :title, :content, :rating, presence: true
  # validates :rating, numericality: { in: (0..5)}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :games
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @booking = Booking.new
    @game = Game.find(params[:game_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @game = Game.find(params[:game_id])
    @booking.game = @game
    @booking.user = current_user

# start_date ne doit pas être antérieure à aujourd'hui
# end_date ne doit pas être antérieure à start_date
# Date ne doit pas déjà être réservée

# quand réservé, marqué tous les jours de la range comme "réservée"
# quand demande de réservation, faire un each sur tous les jours de la range pour comparer avec le statut réservé ou non
# si OK, proceed, si non, message d'erreur

# ne pas oublier de require le module date



# booking_start_date = @booking.start_date
# booking_end_date = @booking.end_date
# range = (booking_start_date..booking_end_date)



# range. each do |day|

# end


# range.include?(Date.new(2012, 10, 5))
# range.include?(Date.new(2012, 11, 1))
# if range


    if @booking.save
      redirect_to game_booking_path(@game, @booking)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @game = Game.find(params[:game_id])
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.save(booking_params)
      redirect_to game_booking_path(@game, @booking)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.save
    redirect_to games_path, status: :see_other ### vérifier le path
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.status = "accepted"
    if @booking.save
      redirect_to dashboard_path
    end
  end

  def deny
    @booking = Booking.find(params[:id])
    @booking.status = "denied"
    if @booking.save
      redirect_to dashboard_path
    end

  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :user_id, :game_id)
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    @games = Game.all

    @search = Game.all
    if params[:query].present?
      sql_subquery = "name ILIKE :query OR description ILIKE :query OR category ILIKE :query"
      @search = @search.where(sql_subquery, query: "%#{params[:query]}%")
    end
  end

  def show
    @game = Game.find(params[:id])
    @review = Review.new
    
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    @game.user = current_user
    if @game.save
      redirect_to game_path(@game)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @game = Game.find(params[:id])
  end

  def update
    @game = Game.find(params[:id])
    if @game.update(game_params)
      redirect_to game_path(@game)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    redirect_to root_path, status: :see_other
  end

  private

  def game_params
    values = params.require(:game).permit(:name, :description, :location, :price, :category, :user_id, :min_number_of_players, :max_number_of_players, :playing_time, photo: [])
    values.delete(:photo) if values[:photo].blank?
    return values
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @games = Game.all

    @search = Game.all
      if params[:query].present?
        sql_subquery = "name ILIKE :query OR description ILIKE :query OR category ILIKE :query"
        @search = @search.where(sql_subquery, query: "%#{params[:query]}%")
      end

  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @game = Game.find(params[:game_id])
    @review.game = @game
    if @review.save
      redirect_to game_path(@game)
    else
      render 'games/show', status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to game_path(@review.game)
  end

  private

  def review_params
    params.require(:review).permit(:rating, :title, :content, :game_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dashboard
    @games = Game.where(user: current_user)
    # @bookings = Booking.where(game_id: @games.pluck(:id))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<% if user_signed_in? == false%>
  <head>
    <meta http-equiv="refresh" content="0; URL=/users/sign_in">
  </head>
<% else%>
  <div class="container my-5">
    <div class="row">
      <div class="col-md-10 mx-auto">
        <div class="card shadow-sm">
          <div class="card-body d-flex">

            <div class="photo-card me-4">
              <% @game.photos.each do |photo| %>
                <%= cl_image_tag photo.key, height: 400, width: 400, crop: :fill, class: "img-fluid" %>
              <% end %>
            </div>
            <div class="details">
              <h1 class="card-title text-primary font-weight-bold mb-3"><%= @game.name.capitalize %></h1>
              <p><strong>Location:</strong> <%= @game.location %></p>
              <p><strong>Price:</strong> <%= @game.price %>€</p>
              <%= link_to 'Annuler', game_path(@game), class: 'btn btn-secondary btn-sm mt-3' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div><div class="container my-5">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="card shadow-sm border-0">
          <div class="card-header bg-primary text-white text-center">
            <h3 class="mb-0">Book your game</h3>
          </div>
          <div class="card-body">
            <%= simple_form_for [@game, @booking] do |f| %>
              <div class="row">
                <div class="col-md-6">
                  <%= f.input :start_date,
                                as: :string,
                                input_html: { data: { controller: "datepicker" } } %>
                  <%#= f.input :start_date, label: "start date", input_html: { class: 'form-control', rows: 4 }, as: :date, html5: true %>
                </div>
                <div class="col-md-6">
                  <%= f.input :end_date,
                                as: :string,
                                input_html: { data: { controller: "datepicker" } } %>
                  <%#= f.input :end_date, label: 'End date', input_html: { class: 'form-control' }, as: :date, html5: true %>
                </div>
              </div>
              <div class="text-center mt-4">
                <%= f.submit 'Réserver mon jeu', id: 'bright', class: 'btn btn-primary btn-lg px-4' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/bookings/show.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-md-10 mx-auto">
      <div class="card shadow-sm">
        <div class="card-body d-flex">

          <div class="photo-card me-4">
            <% @game.photos.each do |photo| %>
              <%= cl_image_tag photo.key, height: 400, width: 400, crop: :fill, class: "img-fluid" %>
            <% end %>
          </div>
          <div class="details">
            <h1 class="card-title text-primary font-weight-bold mb-3"><%= @game.name.capitalize %></h1>
            <p><strong>Location:</strong> <%= @game.location %></p>
            <p><strong>Price:</strong> <%= @game.price %>€</p>
            <%= link_to 'Annuler', game_path(@game), class: 'btn btn-secondary btn-sm mt-3' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div><div class="container my-5">
  <div class="row justify-content-center">
    <div class="col-lg-8">
      <div class="card shadow-sm border-0">
        <div class="card-header bg-primary text-white text-center">
          <h3 class="mb-0">Bookings for this game</h3>
        </div>
        <div class="card-body">
          <% @game.bookings.each do |booking| %>
            <div class="row d-flex flex-inline">
              <div class="col-3"><strong>Start date</strong></div>
              <div class="col-3"><strong>End date</strong></div>
              <div class="col-3"><strong>user</strong></div>
              <div class="col-3"><strong>Status</strong></div>
            </div><div class="row d-flex flex-inline">
              <div class="col-3"><%= booking.start_date %></div>
              <div class="col-3"><%= booking.end_date %></div>
              <div class="col-3"><%= booking.user.first_name %></div>
              <div class="col-3"><%= booking.status %></div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/games/edit.html.erb
<% if user_signed_in? == false%>
  <head>
    <meta http-equiv="refresh" content="0; URL=/users/sign_in">
  </head>
  
<% else%>
  <div class="container my-5">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="card shadow-sm border-0">
          <div class="card-header bg-warning text-dark text-center">
            <h3 class="mb-0">Edit Game Details</h3>
          </div>
          <div class="card-body">
            <%= simple_form_for @game do |f| %>
              <div class="row">
                <div class="col-md-6">
                  <%= f.input :name, label: 'Game Name', input_html: { class: 'form-control' } %>
                </div>
                <div class="col-md-6">
                  <%= f.input :photos, as: :file, label: 'Upload Photos', input_html: { multiple: true, class: 'form-control' } %>
                </div>
              </div>
              <%= f.input :description, label: 'Description', input_html: { class: 'form-control', rows: 4 } %>
              <div class="row">
                <div class="col-md-6">
                  <%= f.input :location, label: 'Location', input_html: { class: 'form-control' } %>
                </div>
                <div class="col-md-6">
                  <%= f.input :price, label: 'Price (€)', input_html: { class: 'form-control' } %>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <%= f.input :min_number_of_players, label: 'Min Players', input_html: { class: 'form-control' } %>
                </div>
                <div class="col-md-6">
                  <%= f.input :max_number_of_players, label: 'Max Players', input_html: { class: 'form-control' } %>
                </div>
              </div>

              <div class="row">
                <div class="col-md-6">
                  <%= f.input :category, label: 'Category', input_html: { class: 'form-control' } %>
                </div>
                <div class="col-md-6">
                  <%= f.input :playing_time, label: 'Playing Time (mins)', input_html: { class: 'form-control' } %>
                </div>
              </div>

              <div class="text-center mt-4">
                <%= f.submit 'Update Game', id: 'bright', class: 'btn btn-warning btn-lg px-4' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end%>

app/views/games/index.html.erb
<div id="searchresults">
  <h1 class="text-white text-center"><strong>Here are some games matching your search:</strong></h1>
    <% if @search.any? %>
      <% @search.each do |result| %>
        <div class="d-inline-flex overflow-hidden p-2"style="">
          <div class="results">
              <% result.photos.each do |photo| %>
                <%= link_to game_path(result), class: "text-decoration-none", :action => 'go' do %>
                  <%= cl_image_tag photo.key, height: 150, width: 150, crop: :fill, class: "img-fluid" %>
                <p><%= result.name%></p>
                <% end %>
              <% end %>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class="text-white"><em>Sorry, no games found... Try another search!</em>
    <% end %>
  </div>
</div>

app/views/games/new.html.erb
<% if user_signed_in? == false%>
  <head>
    <meta http-equiv="refresh" content="0; URL=/users/sign_in">
  </head>
<% else%>

  <div class="container my-5">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="card shadow-sm border-0">
          <div class="card-header bg-primary text-white text-center">
            <h3 class="mb-0">Add a New Game</h3>
          </div>
          <div class="card-body">
            <%= simple_form_for @game do |f| %>
              <div class="row">
                <div class="col-md-6">
                  <%= f.input :name, label: 'Game Name', input_html: { class: 'form-control' } %>
                </div>
                <div class="col-md-6">
                  <%= f.input :photos, as: :file, label: 'Upload Photos', input_html: { multiple: true, class: 'form-control' } %>
                </div>
              </div>

              <%= f.input :description, label: 'Description', input_html: { class: 'form-control', rows: 4 } %>
              <div class="row">
                <div class="col-md-6">
                  <%= f.input :location, label: 'Location', input_html: { class: 'form-control' } %>
                </div>
                <div class="col-md-6">
                  <%= f.input :price, label: 'Price (€)', input_html: { class: 'form-control' } %>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <%= f.input :min_number_of_players, label: 'Min Players', input_html: { class: 'form-control' } %>
                </div>
                <div class="col-md-6">
                  <%= f.input :max_number_of_players, label: 'Max Players', input_html: { class: 'form-control' } %>
                </div>
              </div>

              <div class="row">
                <div class="col-md-6">
                  <%= f.input :category, label: 'Category', input_html: { class: 'form-control' } %>
                </div>
                <div class="col-md-6">
                  <%= f.input :playing_time, label: 'Playing Time (mins)', input_html: { class: 'form-control' } %>
                </div>
              </div>

              <div class="text-center mt-4">
                <%= f.submit 'Save Game', id: 'bright', class: 'btn btn-primary btn-lg px-4' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end%>

app/views/games/show.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-md-10 mx-auto">
      <div class="card shadow-sm">
        <div class="card-body d-flex">

          <div class="photo-card me-4">
            <% @game.photos.each do |photo| %>
              <%= cl_image_tag photo.key, height: 400, width: 400, crop: :fill, class: "img-fluid" %>
            <% end %>
          </div>
          <div class="details">
            <h1 class="card-title text-primary font-weight-bold mb-3"><%= @game.name.capitalize %></h1>
            <p><strong>Description:</strong> <%= @game.description %></p>
            <p><strong>Location:</strong> <%= @game.location %></p>
            <p><strong>Price:</strong> <%= @game.price %>€</p>
            <p><strong>Category:</strong> <%= @game.category %></p>
            <p><strong>Creator:</strong> <%= @game.user.first_name %></p>
            <p><strong>Number of players:</strong> <%= @game.min_number_of_players %> - <%= @game.max_number_of_players %></p>
            <p><strong>Playing Time:</strong> <%= @game.playing_time %> mins</p>
            <%= link_to 'All games', root_path, class: 'btn btn-secondary btn-sm mt-3' %>
            <% if @game.user == current_user %>
            <%= link_to 'Edit this game', edit_game_path(@game), class: 'btn btn-secondary btn-sm mt-3' %>
            <%= link_to 'Delete this game', game_path(@game), data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, method: :delete, class: 'btn btn-secondary btn-sm mt-3' %>
            <% else %>
            <%= link_to 'Book this game', new_game_booking_path(@game), class: 'btn btn-secondary btn-sm mt-3' %>
            <% end %>
            
            <button type="button" class="btn btn-secondary btn-sm mt-3" data-bs-toggle="modal" data-bs-target="#reviewModal">Add a review</button>

            <button type="button" class="btn btn-secondary btn-sm mt-3" data-bs-toggle="modal" data-bs-target="#reviewModal">Add a review</button>
            
            <div class="modal fade" id="reviewModal" tabindex="-1" aria-labelledby="reviewModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="reviewModalLabel">Tell us everything!</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    <%= render 'reviews/form' %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container d-flex justify-content-center">

  <div class="review-container" style="background: rgba(255, 255, 255, 0.8); color: black; padding: 10px; border-radius: 8px; margin-bottom: 15px; ; width: 60%">
    <% if @game.reviews.empty? %>
      <small><em class="text-muted">Be the first one to review this game !</em></small>
    <% else %>
    <h3 class="titre text-center">Reviews</h3>
      <ul class="list-unstyled d-flex" style="padding-bottom: 10px;">
        <% @game.reviews.each do |review| %>
          <li class="review-item" style="border-left: 2px solid black; padding: 20px 20px; margin-right: 10px; height: 200px; display: flex; flex-direction: column; justify-content: space-between; width: 200px; overflow-y: auto;">
            <div>
              <small><em class="text-muted"><%= review.created_at %> ago</em></small>
            </div>
            <h4 class="review-title" style="font-size: 1.5em; margin-bottom: 10px; flex-grow: 0;"> <%= review.title %> </h4>
            <p class="mb-0" style="flex-grow: 1; overflow-y: auto; text-overflow: ellipsis; white-space: nowrap; display: block;"> <%= review.content %> </p>
            <span class="review-rating" style="font-weight: bold; background-color: yellow; padding: 5px; border-radius: 5px;"> <%= review.rating %>/5 </span>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airbnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet"/>

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="main-background"></div>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%# <div class="container mt-6 d-flex"  style="height:50vh;"> %>
<%# <div class="camembert col-9"> camembert</div> %>
<div class="homebox position-relative" style="height: 47vh;">
  <div class="categories">
    <div class="categories_rows">
      <h2>Pick your category</h2>
    </div>
    <div class="categories_rows">
      <div class="categories_item"><h3>Family games</h3></div>
      <div class="categories_item"><h3>One to One</h3></div>
    </div>
    <div class="categories_rows">
      <div class="categories_item"><h3>Escape Game</h3></div>
      <div class="categories_item"><h3>Cardgames</h3></div>
    </div>
  </div>
<%# <div class="presentation-card">
<h3>La première plateforme de location de jeux de société entre particulier. Venez l'essayez vous aussi, vous ne regretterez pas !</h3>
</div> %>
  <!-- Overlay Image -->
  <div class="overlay-image position-absolute" style="top: 60%; left: 86%; transform: translate(-50%, -50%);">
    <img src="https://res.cloudinary.com/dc3qzjv1h/image/upload/v1732202814/review_circle-removebg-preview_shc03e.png" alt="Overlay" style="max-width: 350px; max-height: 350px; display: block; margin: auto;">

    <!-- Text Centered on Image -->
    <div class="text-center position-absolute" style="top: 50%; left: 50%; transform: translate(-50%, -50%); color: white; text-shadow: 2px 2px 5px rgba(0, 0, 0, 0.7);">
      <% if @reviews.present? %>
        <% @reviews.each_with_index do |review, index| %>
          <div class="review-slide <%= 'active' if index == 0 %>" style="animation-delay: <%= index * 5 %>s;">
            <h4 class="mb-3"><%= review.title %></h4>
            <p class="mb-2"><%= truncate(review.content, length: 150) %></p>
            <span class="badge bg-primary"><%= review.rating %>/5</span>
          </div>
        <% end %>
      <% else %>
        <span class="badge bg-primary">5/5</span>
        <p>Excellent moment passés avec ce jeu ! Je recommande !</p>
      <% end %>
    </div>
  </div>
</div>
    <div class="gamesbox">
      <div class="gamesbox__track">
        <div class="gamesbox__grid" data-controller="pages">
          <% @games.each do |game| %>
            <%= link_to game_path(game), class: "text-decoration-none", :action => 'go' do %>
              <div style="height: 20vh; width: 20vh; color: white;" class="gamesbox__item">
                <% game.photos.each do |photo| %>
                  <%= cl_image_tag photo.key, height: 400, width: 400, crop: :fill, class: "img-fluid" %>
                <% end %>
              </div>
              <p style="color: white; font-weight: bold;"><%= game.name %></p>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

app/views/reviews/_form.html.erb
<%= simple_form_for [@game, @review], html: { class: 'form', data: { controller: "rating" } } do |f| %>
  <div class="mb-3">
    <%= f.input :title, label: 'Review Title', input_html: { class: 'form-control' } %>
  </div>
  <div class="mb-3">
    <%= f.input :content, as: :text, label: 'Content', input_html: { class: 'form-control' } %>
  </div>
  <div class="mb-3">
    <%= f.input :rating, as: :hidden, input_html: { id: 'rating_input', data: { rating_target: "hiddenInput" } } %>
    <label for="review_rating" class="form-label">Rating</label>
    <div class="d-flex">
      <div id="star" class="stars">
        <% 1.upto(5) do |i| %>
          <i class="fa fa-star" data-value="<%= i %>" data-action="click->rating#select" data-rating-target="star"></i>
        <% end %>
      </div>
    </div>
  </div>
  <div>
    <%= f.button :submit, 'Submit Review', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/reviews/new.html.erb
    <div><%= render "form" %></div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid d-flex align-items-center">

    <a class="navbar-brand position-fixed top-0">
      <%= link_to cl_image_tag("meyshhjdvhde5mxnoc9y", width: 80, height: 80, crop: :fill), root_path %>
    </a>

    <div>
      <%= form_with url: games_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Search your game!"
          %>
        <%= submit_tag "Search", name: "", class: "btn btn-secondary" %>
      <% end %>
    </div>

    <div>
      <%= link_to new_game_path, style: "text-decoration:none;", :action => 'go' do %>
        <button class="btn btn-warning">Add a new game</button>
      <% end %>
    </div>

    <div>
      <%= link_to dashboard_path, style: "text-decoration:none;", :action => 'go' do %>
        <button class="btn btn-warning">My dashboard</button>
      <% end %>
    </div>

    <!-- Menu and Buttons -->
    <div class="d-flex align-items-center">
      <!-- Dropdown Menu -->
      <%# <div class="dropdown me-3">
        <a class="nav-link dropdown-toggle text-light fw-bold" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Menu
        </a>
        <ul class="dropdown-menu dropdown-menu-end shadow-sm">
          <li><a class="dropdown-item" href="#">Find game</a></li>
          <li> %>
            <%# link_to new_game_path, style: "text-decoration:none;", :action => 'go' do %>
            <%# <p class="dropdown-item">Create a game</p> %>
            <%# end %>
          <%# </li>
          <li><a class="dropdown-item" href="#">Book game</a></li>
          <li><a class="dropdown-item" href="#">See all games</a></li>
        </ul>
      </div> %>
      <!-- Sign-up and Log-in Buttons -->
      <% if current_user %>
        <button class="btn btn-light">
          <%= link_to "Log Out", destroy_user_session_path, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
        </button>
        <% else %>
        <button class="btn btn-light me-2">
        <%= link_to "Sign Up", new_user_registration_path %>
      </button>
      <button class="btn btn-light">
        <%= link_to "Log In", new_user_session_path %>
      </button>
      <% end %>
    </div>
  </div>
</nav>

app/views/users/dashboard.html.erb
<% if user_signed_in? == false%>
  <head>
    <meta http-equiv="refresh" content="0; URL=/users/sign_in">
  </head>
<% else%>

  <div class="container">
    <div class="text-white">
      <h1><%= current_user.first_name %></h1>
      <h2>Dashboard</h2>
    </div>
    <div>
      <div class="text-white"><h3>All my games</h3></div>
      <% @games.each do |game| %>
        <div class="card-product">
            <div class="card-product-img-div">
              <% game.photos.each do |photo| %>
                <%= cl_image_tag photo.key, height: 400, width: 400, crop: :fill%>
              <% end %>
            </div>
          <div class="card-product-infos">
            <h2><%= game.name %></h2>
            <p><%= game.description %></p>
            <div class="bookingtable">
              <div class="bookingheader">
                <div class="bookingheadercells"><h2>Player</h2></div>
                <div class="bookingheadercells"><h2>Start date</h2></div>
                <div class="bookingheadercells"><h2>End date</h2></div>
                <div class="bookingheadercells"><h2>Status</h2></div>
              </div>
              <% game.bookings.each do |booking| %>
                <div class="bookinglines">
                  <div class="bookinglinescells"><p><%= booking.user.first_name %></p></div>
                  <div class="bookinglinescells"><p><%= booking.start_date %></p></div>
                  <div class="bookinglinescells"><p><%= booking.end_date %></p></div>
                  <% if booking.status == "denied" %>
                    <div class="bookinglinescells" id="lastcell"><p class="statusdenied">refused</p></div>
                  <% elsif booking.status == "accepted" %>
                    <div class="bookinglinescells" id="lastcell"><p class="statusaccepted">accepted</p></div>
                  <% else %>
                    <div class="bookinglinescells" id="lastcell"><p><%= link_to 'accept', accept_booking_path(booking.id), data: {turbo_method: :patch }, class: "accept pending" %>  <%= link_to 'deny', deny_booking_path(booking.id), data: {turbo_method: :patch }, class: "deny pending" %></p></div>
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<%end%>